[[redirects]]
  from = "/robots.txt"
  to = "/robots_site.txt"
  status = 200
  force = true

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200
  force = true

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain"
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"
    Cache-Control = "no-cache, no-store, must-revalidate"
